"""update reports for user ownership and location privacy

Revision ID: 2368776c27a5
Revises: 2847d42a1ca7
Create Date: 2026-08-26 22:45:42.873946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2368776c27a5'
down_revision: Union[str, Sequence[str], None] = '2847d42a1ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('reporter_user_id', sa.Uuid(), nullable=False))
    op.add_column('reports', sa.Column('location_visibility', sa.Text(), nullable=False))
    op.create_foreign_key(
    "fk_reports_reporter_user_id",
    "reports",
    "users",
    ["reporter_user_id"],
    ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'location_visibility')
    op.drop_column('reports', 'reporter_user_id')
    # ### end Alembic commands ###
