"""add report coordinates

Revision ID: 6492cd241d28
Revises: 85f18c1793af
Create Date: 2026-08-16 12:59:20.376806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6492cd241d28'
down_revision: Union[str, Sequence[str], None] = '85f18c1793af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    # ### end Alembic commands ###
